name: mob_2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  supabase_flutter: ^2.12.4
  bcrypt: ^1.2.0
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  cloud_firestore: ^6.4.0
  google_sign_in: ^6.1.0
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.10.0

dependency_overrides:
  app_links: 6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/pohon1.png
    - assets/gp.png
    - assets/group1.png
    - assets/fb.png
    - assets/google.png
    - assets/icon.png
